EXE_NAME = GregBuild.exe
DIST_DIR = ../dist
LIB=./lib
USR_BIN_DIR = /usr/bin
DIST_EXE = $(DIST_DIR)/$(EXE_NAME)
USR_BIN_EXE = $(USR_BIN_DIR)/GB.exe
EXAMPLE_LIB = ../ExampleSrcRepo/lib
GREG_TEST_DLL = GregTest.dll
EXTERNAL_GREG_TEST_DLL = external/GregTest/dist/$(GREG_TEST_DLL)
EXAMPLE_LIB_GREG_TEST_DLL = $(EXAMPLE_LIB)/$(GREG_TEST_DLL)
SOURCES := $(shell find . -name "*.c" ! -path */external/*)
OBJECTS=$(patsubst %.c,%.o,$(SOURCES))
PLUGINS_DIR = $(DIST_DIR)/Plugins
TIME_TRACKING_PLUGIN_SOURCES := $(shell find plugins/TimeTrackingPlugin -name "*.c")

CORE=./core
CORE_APPLICATION=$(CORE)/application
CORE_APPLICATION_SOURCES=$(shell find $(CORE_APPLICATION) -name "*.c")
CORE_APPLICATION_OBJ=$(LIB)/application.o

CORE_FILE_SYSTEM_RECURSION=$(CORE)/fileSystemRecursion
CORE_FILE_SYSTEM_RECURSION_SOURCES=$(shell find $(CORE_FILE_SYSTEM_RECURSION) -name "*.c")
CORE_FILE_SYSTEM_RECURSION_OBJ=$(LIB)/fileSystemRecursion.o

CORE_MAIN=$(CORE)/main
CORE_MAIN_SOURCES=$(shell find $(CORE_MAIN) -name "*.c")
CORE_MAIN_OBJ=$(LIB)/main.o

CORE_TEST_MAIN_WRITING=$(CORE)/testMainWriting
CORE_TEST_MAIN_WRITING_SOURCES=$(shell find $(CORE_TEST_MAIN_WRITING) -name "*.c")
CORE_TEST_MAIN_WRITING_OBJ=$(LIB)/testMainWriting.o

TOOLKIT=external/GregCToolkit
TOOLKIT_SW=$(TOOLKIT)/sw
TOOLKIT_LIB=$(TOOLKIT)/lib
TOOLKIT_COLLECTIONS=$(TOOLKIT_SW)/Collections
TOOLKIT_COMMAND_LINE_OPTIONS=$(TOOLKIT_SW)/CommandLineOptions
TOOLKIT_EXTERNAL_PROGRAM_EXECUTION=$(TOOLKIT_SW)/ExternalProgramExecution
TOOLKIT_FILE_SYSTEM=$(TOOLKIT_SW)/FileSystem
TOOLKIT_STRING=$(TOOLKIT_SW)/String
TOOLKIT_SOURCES=$(shell find external/GregCToolkit -name "*.c")
TOOLKIT_OBJECTS=$(patsubst %.c,%.o,$(TOOLKIT_SOURCES))
TOOLKIT_LIB_OBJECTS=$(addprefix $(TOOLKIT_LIB)/,$(notdir $(TOOLKIT_OBJECTS)))

LIB_OBJECTS = $(CORE_APPLICATION_OBJ) \
			  $(CORE_FILE_SYSTEM_RECURSION_OBJ) \
			  $(CORE_MAIN_OBJ) \
			  $(CORE_TEST_MAIN_WRITING_OBJ) \	

$(DIST_EXE): $(LIB_OBJECTS) $(TOOLKIT_LIB_OBJECTS)
	# Compile GregBuild 
	gcc -o $@ $^
	cp $(DIST_EXE) $(USR_BIN_EXE)

############################################################################
######						GregBuild src Rules						  ######
############################################################################

$(CORE_APPLICATION_OBJ): $(CORE_APPLICATION_SOURCES)
	gcc -c $^

$(CORE_FILE_SYSTEM_RECURSION_OBJ): $(CORE_FILE_SYSTEM_RECURSION_SOURCES)
	gcc -c $^

$(CORE_MAIN_OBJ): $(CORE_MAIN_SOURCES)
	gcc -c $^

$(CORE_TEST_MAIN_WRITING_OBJ): $(CORE_TEST_MAIN_WRITING_SOURCES)
	gcc -c $^

############################################################################
######						Toolkit src Rules						  ######
############################################################################

$(TOOLKIT_LIB)/%.o: $(TOOLKIT_OBJECTS)
	cp $^ $(TOOLKIT_LIB)

$(TOOLKIT_COLLECTIONS)/%.o: $(TOOLKIT_COLLECTIONS)/%.c
	gcc -c -o $@ $<

$(TOOLKIT_COMMAND_LINE_OPTIONS)/%.o: $(TOOLKIT_COMMAND_LINE_OPTIONS)/%.c
	gcc -c -o $@ $<

$(TOOLKIT_EXTERNAL_PROGRAM_EXECUTION)/%.o: $(TOOLKIT_EXTERNAL_PROGRAM_EXECUTION)/%.c
	gcc -c -o $@ $<

$(TOOLKIT_FILE_SYSTEM)/%.o: $(TOOLKIT_FILE_SYSTEM)/%.c
	gcc -c -o $@ $<

$(TOOLKIT_STRING)/%.o: $(TOOLKIT_STRING)/%.c
	gcc -c -o $@ $<


############################################################################
######						Plugin/Misc Rules						  ######
############################################################################

$(EXAMPLE_LIB_GREG_TEST_DLL): $(EXAMPLE_LIB)
	#Copying GregTest.dll to ../ExampleSrcRepo/lib
	cp $(EXTERNAL_GREG_TEST_DLL) $(EXAMPLE_LIB_GREG_TEST_DLL)

Plugins: $(PLUGINS_DIR)
	gcc -shared $(TIME_TRACKING_PLUGIN_SOURCES) -o $(PLUGINS_DIR)/TimeTrackingPlugin.dll

$(DIST_DIR):
	mkdir  -p $(DIST_DIR)

$(EXAMPLE_LIB):
	mkdir -p $(EXAMPLE_LIB)

$(TOOLKIT_LIB):
	mkdir -p $(TOOLKIT_LIB)

$(PLUGINS_DIR):
	mkdir -p $(PLUGINS_DIR)


############################################################################
######						Clean Rules								  ######
############################################################################

clean:
	rm $(TOOLKIT_LIB)/*.o
	rm $(EXAMPLE_LIB)/*.o
	rm $(USR_BIN_EXE)
	rm $(DIST_EXE)